FROM golang:1.18 as builder

WORKDIR /go/src/github.com/Pranc1ngPegasus/bazel-grpc-gateway-practice

COPY . .

RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -o app ./cmd/server

FROM alpine:latest as executor
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /go/src/github.com/Pranc1ngPegasus/bazel-grpc-gateway-practice/app .
CMD ["./app"]
