// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Pranc1ngPegasus/bazel-grpc-gateway-practice/adapter/configuration"
	"github.com/Pranc1ngPegasus/bazel-grpc-gateway-practice/adapter/handler"
	"github.com/Pranc1ngPegasus/bazel-grpc-gateway-practice/adapter/repository"
	"github.com/Pranc1ngPegasus/bazel-grpc-gateway-practice/adapter/server"
	"github.com/Pranc1ngPegasus/bazel-grpc-gateway-practice/infrastructure"
	"github.com/Pranc1ngPegasus/bazel-grpc-gateway-practice/usecase"
)

// Injectors from inject.go:

func initialize() server.GrpcServer {
	config := configuration.Get()
	rdbConnector := infrastructure.NewRDBConnector(config)
	user := repository.NewUser(rdbConnector)
	createUser := usecase.NewCreateUser(user)
	createUserProvider := handler.NewCreateUserProvider(createUser)
	userServiceV1 := handler.NewUserServiceV1(createUserProvider)
	grpcServer := server.NewGrpcServer(config, userServiceV1)
	return grpcServer
}
