name: Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup bazelisk
        uses: bazelbuild/setup-bazelisk@v1

      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel

      - name: Build
        run: make bazel-build

      - name: check git diff
        run: |
          if ! git diff --exit-code --quiet
          then
            exit 1
          fi
